### ISSUE TITLE
Add `light-my-request` generator.

### ISSUE THREAD

**Issue by arthurfiorette** [scalar/snippetz#15]
https://github.com/fastify/light-my-request

Light my request is an awesome tool to execute requests against your own API without going to the network, normally inside e2e/unit tests. 

Being able to copy light-my-request inject calls from this generator would help writing e2e/unit tests a lot.

**Comment by hanspagel** [comment]
Moved to `scalar/scalar`: https://github.com/scalar/scalar/issues/2960
